SELECT
	tabs.TABLE_SCHEMA,
	tabs.TABLE_NAME,
	cols.COLUMN_NAME,
	cols.ORDINAL_POSITION,
	cols.DATA_TYPE
FROM
	INFORMATION_SCHEMA.tables tabs
	INNER JOIN INFORMATION_SCHEMA.COLUMNS cols
	ON tabs.TABLE_NAME = cols.TABLE_NAME AND
	tabs.TABLE_SCHEMA = cols.TABLE_SCHEMA
WHERE
	tabs.TABLE_TYPE = 'BASE TABLE'
ORDER BY
	tabs.table_name,
	cols.ORDINAL_POSITION
