name: Generate Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Directory Indices 
        uses: DaanV2/Markdown-Action-Create-Indexes@v1.5.13
        with: 
          folder: ${{github.workspace}}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: ./cliff.toml
          args: --verbose
        env:
          OUTPUT: ./CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
        
      - name: Commit and Push Changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
    
    
