name: Index Directories
on:
  push:
    branches: [ main ]
jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: DaanV2/Markdown-Action-Create-Indexes@v1.5.13
        with: 
          folder: ${{github.workspace}}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated markdown-index Documentation
          file_pattern: "**/*.md"
